name: Build precompiled NIFs

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}

    strategy:
      fail-fast: false
      matrix:
        nif: ["2.15", "2.16", "2.17"]
        job:
          - { target: aarch64-apple-darwin, os: macos-14 }
          - { target: x86_64-apple-darwin, os: macos-14 }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
          - { target: x86_64-pc-windows-gnu, os: windows-2022 }
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version from tag
        shell: bash
        run: echo "PROJECT_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Install cross-compilation target
        if: matrix.job.target == 'x86_64-apple-darwin' && runner.arch == 'ARM64'
        run: rustup target add x86_64-apple-darwin

      - name: Build precompiled NIF
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: signer_nif
          project-dir: native/signer
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross }}
          variant: ""

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            signer_nif-*
